# ------------------------------------------------------------------------------
# Use this file only to develop with your local Aether images
# (not the docker hub ones), change the ${AETHER_PATH} and ${AETHER_SDK_PATH}
# values to your current ones.
#
# docker-compose -f docker-compose-local.yml build
# docker-compose -f docker-compose-local.yml up
#
# ------------------------------------------------------------------------------

version: "2.1"

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24

volumes:
  gather_local_database_data: {}
  gather_local_minio_data: {}

services:

  # ---------------------------------
  # Databases
  # ---------------------------------

  db:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: postgres-base
    volumes:
      - gather_local_database_data:/var/lib/postgresql/data
    networks:
      - local

  minio:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: minio-base
    volumes:
      - gather_local_minio_data:/data
    networks:
      - local


  # ---------------------------------
  # NGINX
  # ---------------------------------

  nginx:
    extends:
      file: ./docker-compose-base.yml
      service: nginx-base
    networks:
      local:
        ipv4_address: 192.168.33.10
    extra_hosts:
      - aether.local:127.0.0.1
      - gather.local:127.0.0.1


  # ---------------------------------
  # Aether kernel
  # ---------------------------------

  kernel:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: kernel-base
    environment:
      KEYCLOAK_SERVER_URL: null
    volumes:
      # - ${AETHER_SDK_PATH:-../aether-django-sdk-library}/aether/sdk:/usr/local/lib/python3.7/site-packages/aether/sdk
      # - ${AETHER_PYTHON_PATH:-../aether-python-library}/aether/python:/usr/local/lib/python3.7/site-packages/aether/python
      - ./.persistent_data/backups/kernel:/backups
      - ./.persistent_data/static/kernel:/var/www/static
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - local
    extra_hosts:
      - aether.local:192.168.33.10
      - gather.local:192.168.33.10


  # ---------------------------------
  # Aether ODK module
  # ---------------------------------

  odk:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: odk-base
    environment:
      AETHER_KERNEL_URL: http://aether.local/kernel
      KEYCLOAK_SERVER_URL: null
    volumes:
      # - ${AETHER_SDK_PATH:-../aether-django-sdk-library}/aether/sdk:/usr/local/lib/python3.7/site-packages/aether/sdk
      - ./.persistent_data/backups/odk:/backups
      - ./.persistent_data/static/odk:/var/www/static
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_healthy
      minio:
        condition: service_started
      kernel:
        condition: service_started
    networks:
      - local
    extra_hosts:
      - aether.local:192.168.33.10
      - gather.local:192.168.33.10


  # ---------------------------------
  # Aether UI
  # ---------------------------------

  ui-assets:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: ui-assets-base
    networks:
      - local

  ui:
    extends:
      file: ${AETHER_PATH:-../aether}/docker-compose-base.yml
      service: ui-base
    environment:
      AETHER_KERNEL_URL: http://aether.local/kernel
      KEYCLOAK_SERVER_URL: null
    volumes:
      # - ${AETHER_SDK_PATH:-../aether-django-sdk-library}/aether/sdk:/usr/local/lib/python3.7/site-packages/aether/sdk
      - ./.persistent_data/backups/ui:/backups
      - ./.persistent_data/static/ui:/var/www/static
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_healthy
      kernel:
        condition: service_started
    networks:
      - local
    extra_hosts:
      - aether.local:192.168.33.10
      - gather.local:192.168.33.10


  # ---------------------------------
  # Gather Assets
  # ---------------------------------

  gather-assets:
    extends:
      file: ./docker-compose-base.yml
      service: gather-assets-base
    networks:
      - local


  # ---------------------------------
  # Gather
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    # volumes:
    #   - ${AETHER_SDK_PATH:-../aether-django-sdk-library}/aether/sdk:/usr/local/lib/python3.7/site-packages/aether/sdk
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_healthy
      kernel:
        condition: service_started
      odk:
        condition: service_started
      gather-assets:
        condition: service_started
    networks:
      - local
    extra_hosts:
      - aether.local:192.168.33.10
      - gather.local:192.168.33.10
