version: "2.1"

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db-test:
    extends:
      file: ./docker-compose-base.yml
      service: postgres-base

  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel-test:
    extends:
      file: ./docker-compose-base.yml
      service: kernel-base
    environment:
      TESTING: "true"
      RDS_DB_NAME: aether-kernel-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9000
    ports:
      - "9000:9000"
    depends_on:
      - db-test
    command: start_dev

  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk-test:
    extends:
      file: ./docker-compose-base.yml
      service: odk-base
    environment:
      TESTING: "true"
      AETHER_KERNEL_URL: http://kernel-test:9000
      RDS_DB_NAME: aether-odk-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9443
    ports:
      - "9443:9443"
    depends_on:
      - db-test
      - kernel-test
    command: start_dev

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather-test:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    environment:
      TESTING: "true"
      AETHER_MODULES: "kernel,odk,"
      AETHER_KERNEL_URL: http://kernel-test:9000
      AETHER_ODK_URL: http://odk-test:9443
      RDS_DB_NAME: gather-test
      RDS_HOSTNAME: db-test
      WEB_SERVER_PORT: 9005
    ports:
      - "9005:9005"
    depends_on:
      - db-test
      - kernel-test
      - odk-test
    command: test

  # ---------------------------------
  # Gather Assets container
  # ---------------------------------

  gather-assets-test:
    extends:
      file: docker-compose-base.yml
      service: gather-assets-base
    command: test
